import { StyleSheet } from 'react-native';

import { DemoFonts } from './fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  loadingScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenScrollContent: {
    paddingBottom: 20,
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 6,
  },
  title: {
    fontSize: 24,
    fontFamily: DemoFonts.extraBold,
    color: '#0F172A',
    flexShrink: 1,
  },
  subtitle: {
    fontSize: 14,
    color: '#475569',
    fontFamily: DemoFonts.regular,
  },
  tabList: {
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  tabItem: {
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: '#E2E8F0',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    gap: 5,
  },
  tabItemActive: {
    backgroundColor: '#0F172A',
    borderColor: '#0F172A',
  },
  tabTitle: {
    fontSize: 14,
    fontFamily: DemoFonts.semibold,
    color: '#0F172A',
  },
  tabTitleActive: {
    color: '#F8FAFC',
  },
  tabSubtitle: {
    fontSize: 12,
    color: '#475569',
    fontFamily: DemoFonts.regular,
  },
  tabSubtitleActive: {
    color: '#E2E8F0',
  },
  demoStage: {
    paddingHorizontal: 16,
  },
  demoContainer: {
    borderRadius: 16,
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 12,
  },
  demoTitle: {
    fontSize: 18,
    fontFamily: DemoFonts.semibold,
    color: '#0F172A',
  },
  demoDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: '#334155',
    fontFamily: DemoFonts.regular,
  },
  rowButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  demoActionButton: {
    minWidth: 130,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  demoActionButtonPressed: {
    opacity: 0.78,
  },
  demoActionButtonText: {
    color: '#0F172A',
    fontSize: 13,
    textAlign: 'center',
    fontFamily: DemoFonts.semibold,
  },
  controlGroup: {
    gap: 6,
  },
  controlLabel: {
    fontSize: 12,
    fontFamily: DemoFonts.semibold,
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  paletteSelectorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  paletteButton: {
    minWidth: 96,
    flexGrow: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
  },
  paletteButtonActive: {
    borderColor: '#0F172A',
    backgroundColor: '#E2E8F0',
  },
  paletteButtonTitle: {
    fontSize: 12,
    fontFamily: DemoFonts.semibold,
    color: '#0F172A',
  },
  palettePreviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  palettePreviewDot: {
    width: 12,
    height: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(15, 23, 42, 0.2)',
  },
  modeSelectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  modeSelectorButton: {
    minWidth: 88,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeSelectorButtonActive: {
    borderColor: '#0F172A',
    backgroundColor: '#0F172A',
  },
  modeSelectorButtonText: {
    fontSize: 12,
    fontFamily: DemoFonts.semibold,
    color: '#334155',
  },
  modeSelectorButtonTextActive: {
    color: '#F8FAFC',
  },
  customDot: {
    width: 16,
    height: 6,
    borderRadius: 99,
  },
  customCloseButton: {
    minWidth: 62,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  customCloseText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: DemoFonts.semibold,
  },
  customImage: {
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#0EA5E9',
    overflow: 'hidden',
  },
  customPlaceholder: {
    width: 220,
    height: 220,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#FB7185',
    backgroundColor: '#FFF1F2',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    gap: 6,
  },
  customPlaceholderTitle: {
    fontSize: 14,
    fontFamily: DemoFonts.semibold,
    color: '#BE123C',
  },
  customPlaceholderText: {
    fontSize: 12,
    color: '#9F1239',
    textAlign: 'center',
    fontFamily: DemoFonts.regular,
  },
  customPlaceholderPath: {
    fontSize: 10,
    color: '#881337',
    textAlign: 'center',
    fontFamily: DemoFonts.regular,
  },
  customCheckRow: {
    height: 34,
    borderRadius: 999,
    backgroundColor: '#0EA5E9',
    marginTop: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  customCheckIndicator: {
    fontSize: 13,
    fontFamily: DemoFonts.semibold,
    color: '#FFFFFF',
  },
  customCheckLabel: {
    fontSize: 12,
    fontFamily: DemoFonts.medium,
    color: '#FFFFFF',
  },
  storageInfo: {
    fontSize: 12,
    color: '#334155',
    fontFamily: DemoFonts.regular,
  },
});
